### ISSUE TITLE
WARNING:root:Error loading bans from disk. [Errno 2] No such file or directory: '/data/bans.json'

### ISSUE THREAD

**Issue by rtho782** [AndrewPaglusch/Plex-Duplicate-Stream-Killer#12]
I think I have everything installed correctly, but it's upset there is no bans.json.

If I manually create it (touch bans.json) it complains it is empty.

Should the script not create this file?

![image](https://user-images.githubusercontent.com/25555587/225155203-22c5ea40-b071-4d2f-88d5-dce4e3a1a0a2.png)

**Comment by rtho782** [comment]
<img width="625" alt="image" src="https://user-images.githubusercontent.com/25555587/225155656-65421afd-6da1-429e-89f1-be2e92850831.png">

**Comment by AndrewPaglusch** [comment]
@rtho782 Thanks for reporting this. I will try to reproduce the problem this week.

**Comment by rtho782** [comment]
I have solved it by putting dummy json data in the `data.json` file as follows:

`{"user":"none", "ban_length_hrs":"0"}`

I feel like I know almost enough to be dangerous here but not quite enough to actually know what I am doing :D

**Comment by rtho782** [comment]
Hm, it doesn't seem to actually ban people tho.

**Comment by AndrewPaglusch** [comment]
The message you're seeing is a warning and can safely be ignored. I will update the message to be more descriptive, as the current message is very misleading and indicates something is wrong. When someone gets banned, the `bans.json` file will be created at `/data/bans.json` (inside the container). The script will continue to run, even if the file is not found on startup.

You also mentioned that people are not being banned. Can you please tell me how you're testing this and what the script output shows when someone should be banned (and isn't)? Just a reminder that Plex Pass is required for this script to work (documented [here](https://github.com/AndrewPaglusch/Plex-Duplicate-Stream-Killer/blob/8dd7840a6040cc0bc5c3f9ba5e95c8609a217409/README.md?plain=1#L10)). The ability to kill streams is only available to Plex Pass users. Thanks!

**Comment by AndrewPaglusch** [comment]
v2.0.2 has the improved message

**Comment by AndrewPaglusch** [comment]
@rtho782 Do you have any updates to share?

**Comment by rtho782** [comment]
Sorry, yes, it is working, I think I just misinterpreted the earlier error :)

**Comment by AndrewPaglusch** [comment]
I'm happy to hear that it's working for you. I'll go ahead and close this now.
