### ISSUE TITLE
ERROR:root:Error getting streams from Plex: 'device'

### ISSUE THREAD

**Issue by ArbiterGR** [AndrewPaglusch/Plex-Duplicate-Stream-Killer#14]
Hello, i'm getting the following error when someone streams on my plex server"
ERROR:root:Error getting streams from Plex: 'device'

If i access the status url directly on my web browser eg http://url:32400/status/sessions?X-Plex-Token=PLEXTOKEN i can correctly see the xml file getting populated with session data.

My plex token is correct and the container connects to my plex instance. What could be wrong here ?

**Comment by AndrewPaglusch** [comment]
Can you please post the full traceback of the error?

**Comment by ArbiterGR** [comment]
> Can you please post the full traceback of the error?

The logs do not output the full traceback, all i get is this:
![image](https://user-images.githubusercontent.com/3236764/229582232-7d702b1c-9011-4455-b7d7-a04cb197fca0.png)

Is there any way to get the full traceback?

**Comment by AndrewPaglusch** [comment]
This is very strange. As you can see [here](https://github.com/AndrewPaglusch/Plex-Duplicate-Stream-Killer/blob/5a4a28da52753866521dc83beabead401b707ee5/app/run.py#L26), the `err` variable should be printed out. I'm not sure why 'device' is being printed.

Please try the following:

1. `docker exec -it dupstreamkiller sed -i 's|logging.error(f"Error getting|logging.exception(f"Error getting|g' run.py`
2. `docker restart dupstreamkiller`
3. `docker logs --tail 50 -f dupstreamkiller`

This should cause a full traceback to be printed, along with the error. Please post that to this issue.

**Comment by ArbiterGR** [comment]
Thank you for the response, this is what i get:

```
ERROR:root:Error getting streams from Plex: 'device'
Traceback (most recent call last):
  File "/app/run.py", line 21, in get_streams
    return _parse_streams(jstreams)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/run.py", line 79, in _parse_streams
    'device': stream['Player']['device'],
              ~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'device'
```

**Comment by ArbiterGR** [comment]
What is weirder, is that it seems i can get it to work only if i use plex via app.plex.tv . If i view media using its apps (i tried windows client and android client) i get the above error. 

To prove that, i sucessfully banned myself by using app.plex.tv from my pc and from my mobile phone (using mobile data)

**Comment by AndrewPaglusch** [comment]
Interesting. You have someone streaming, but Plex isn't returning what kind of device they're using. It's completely omitted from the JSON response. I haven't seen this until now. 

Please do the following and see if it fixes the issue:

1. `docker exec -it dupstreamkiller sed -i "s|stream\['Player'\]\['device'\]|stream\['Player'\].get('device', 'Unknown')|g" run.py`
2. `docker restart dupstreamkiller`
3. `docker logs --tail 50 -f dupstreamkiller`

**Comment by ArbiterGR** [comment]
That worked! 

Trying to ban myself got this: 
`INFO:root:(Stream 0) DEVICE: "SM-S908B" IPADDR: "_xxx.xxx.xxx..xx_" MEDIA: "A Stolen Truck and Going on the Lam"
INFO:root:(Stream 1) DEVICE: "Unknown" IPADDR: "10.10.1.2" MEDIA: "Chapter 1: The Mandalorian"`

~~I don't know why the plex windows client gets reported as "unknown" (should output my pc's hostname)~~ edit: that's because of the edit on the run.py, it now returns unknown if the device name does not get returned:P, but it works now.

Thank you

**Comment by AndrewPaglusch** [comment]
Great! I'm glad that worked. The fix is not permanent at this point, and will be reverted if you re-create the container.

I will go ahead and make the changes and cut a new release so they will be permanent.

**Comment by ArbiterGR** [comment]
That's great! Thanks!
