### ISSUE TITLE
[Suggestion] Geolocation Ban

### ISSUE THREAD

**Issue by primetime43** [AndrewPaglusch/Plex-Duplicate-Stream-Killer#3]
Hey, I was wondering if maybe you could add the ability to ban for IPs based on geolocation. For example, if the IP's geolocation is out of state, block it.

**Comment by AndrewPaglusch** [comment]
Good idea! I will look into this and consider implementing it if it doesn't add too much complexity to the script.

**Comment by primetime43** [comment]
It's okay, I just decided to write my own haha.
