### ISSUE TITLE
Unable to parse config.ini

### ISSUE THREAD

**Issue by rtho782** [AndrewPaglusch/Plex-Duplicate-Stream-Killer#32]
Hi :)

This has been working for me for ages, with no changes to settings, but has recently developed the following issue:

![image](https://github.com/AndrewPaglusch/Plex-Duplicate-Stream-Killer/assets/25555587/85f378c5-9ed7-4973-ab4e-8c8088b88dba)

I've deleted and readded the container, but not managed to achieve anything. I can't get a command line in the container as it won't start.

Any chance this means anything to you?

**Comment by AndrewPaglusch** [comment]
Hey @rtho782 thanks for the bug report. It looks like it's having issues parsing a setting to an integer - possibly due to a space, an empty string, or an extra character in the setting. Can you post your `docker-compose.yml` config? Make sure to remove private info before posting it

**Comment by rtho782** [comment]
Fixed it, issue was because my config was old and didn't have entries for the ban history stuff, I must have updated recently :D
