### ISSUE TITLE
Feature: 4k Video Transcode

### ISSUE THREAD

**Issue by bakes82** [AndrewPaglusch/Plex-Duplicate-Stream-Killer#7]
Could you add an option to ban 4k video transcode, would prevent having to use taut.

**Comment by AndrewPaglusch** [comment]
Thank you for your suggestion! Let me look into this and see if this would be a feature I would be willing to add on.

**Comment by bakes82** [comment]
Well if you are calling the session URL:

You can look for videoDecision="transcode" and if you wanted to be real easy the sourceVideoCodec="hevc",  This would kill any HVEC transcodes which HVEC has higher CPU requirements, but it would still allow for audio transcodes,  I guess allow toggle for audio/video?  I think in the "Part" node you can see display="4k xxxxxxxx" if you wanted to do more complex checking.  But for me the HVEC/video transcode would be amazing, maybe make it a separate script in case you dont want to kill duplicate streams or add toggle.


This is an example of a h264 transcode.
```xml
<TranscodeSession key="/transcode/sessions/x3nuhw1w5b8ea1h2wm2qu61q" throttled="0" complete="0" progress="2.2999999523162842" size="-22" speed="14.300000190734863" error="0" duration="2649024" remaining="179" context="streaming" sourceVideoCodec="h264" sourceAudioCodec="aac" videoDecision="transcode" audioDecision="transcode" protocol="dash" container="mp4" videoCodec="h264" audioCodec="aac" audioChannels="2" transcodeHwRequested="1" transcodeHwDecoding="vaapi" transcodeHwEncoding="vaapi" transcodeHwDecodingTitle="Intel (VA API)" transcodeHwFullPipeline="1" transcodeHwEncodingTitle="Intel (VA API)" timeStamp="1641229739.4667854" maxOffsetAvailable="568.02635969302639" minOffsetAvailable="504.00399780273438"/>

**Comment by AndrewPaglusch** [comment]
@bakes82 - Thank you for your suggestion, but this is not a feature I will be adding. The sole purpose of this application is to prevent duplicate streams (account sharing), and this feature would not align with that.
